name: Release qBittorrent

on:
  push:
    tags:
      - v*.*.*

jobs:
  build:
    # make readline library is same to zimaos
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch all tags
        run: git fetch --force --tags

      - name: Get version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: make raw page
        run: ./build_raw.sh
    
      - name: '更新 Update release'
        uses: zhanghengxin/git-release-private@ice
        with:
            token: ${{ secrets.CICD_GITHUB_TOKEN }}
            allow_override: true
            gzip: false
            prerelease: true
            tag: ${{ steps.get_version.outputs.VERSION }}
            files: ./qbittorrent.raw